### ISSUE TITLE
install driver before checking model

### ISSUE THREAD

**Issue by AngeDieu** [Omega-Numworks/Omega-Guide#33]
**Pages with issue(s)**
[get started](https://guide.getomega.dev/get-started) and idem in french

**Description of the issue(s)**
I would be preferable if the _**Section IV - Install the driver**_ is before the _**Section I - Model check**_.
Hence, if somebody follows the guide step by step, he will see he has a N0100 for example, and then he will pas the rest of the page  and the driver installation, therfore, he will have problems installing the firmware of his choice as he hasn't installed the driver.

**Comment by Rathmox** [comment]
Fixed.
I added a Prerequesties section at the beggining that includes the driver

**Comment by AngeDieu** [comment]
Thanks
