### ISSUE TITLE
Drivers for numworks N0120

### ISSUE THREAD

**Issue by ADHyperActive** [Omega-Numworks/Omega-Guide#92]
After some quick searches on GitHub, I found the drivers for the MCU that the N0120 uses [here](https://github.com/STMicroelectronics/stm32h7xx-hal-driver/tree/6f5e35e30ac09ba7bf44139a97b289d3df53cf9c).

**Comment by Alerymin** [comment]
This is not the right place to share that content.

If this allows recreating ion for the n0120 and by extension, allows porting Epsilon 15.5.0 and before to n0120, it's interesting but I'm pretty sure devs know about this repo anyway and there is more to do than just copying files.

If you want to contribute don't hesitate to join the discord server.
